# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '8.0'
def shared_pods
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'
end
target 'NativeStarterKit' do
  shared_pods
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for NativeStarterKit

  target 'NativeStarterKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
